language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - python -c "import nltk; nltk.download('stopwords')"
script:
  - coverage run --source=youtube_discusion_tree_api  -m unittest
after-success:
  - coveralls
